-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

-- Install uuid module so that it can be used to generate primary key
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- For card set
CREATE TYPE view  AS ENUM ('private', 'public');

CREATE TABLE IF NOT EXISTS public.vfc
(
    vfc_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    vfc_set_id uuid NOT NULL,
    vfc_question character varying(255) COLLATE pg_catalog."default" NOT NULL,
    vfc_answer character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT vflashcard_pkey PRIMARY KEY (vfc_id)
);

CREATE TABLE IF NOT EXISTS public.vfc_set
(
    vfc_set_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    vfc_user_id uuid NOT NULL,
    vfc_set_title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    vfc_set_access view NOT NULL DEFAULT 'private'::view,
    CONSTRAINT vflashcard_set_pkey PRIMARY KEY (vfc_set_id)
);

CREATE TABLE IF NOT EXISTS public.vfc_user
(
    vfc_user_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    vfc_user_fname character varying(127) COLLATE pg_catalog."default",
    vfc_user_lname character varying(127) COLLATE pg_catalog."default" NOT NULL,
    vfc_user_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    vfc_user_password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT vfc_user_pkey PRIMARY KEY (vfc_user_id),
    CONSTRAINT vfc_user_email_key UNIQUE (vfc_user_email)
);

ALTER TABLE IF EXISTS public.vfc
    ADD CONSTRAINT fk_vfc_set_id FOREIGN KEY (vfc_set_id)
    REFERENCES public.vfc_set (vfc_set_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vfc_set
    ADD CONSTRAINT fk_vfc_user_id FOREIGN KEY (vfc_user_id)
    REFERENCES public.vfc_user (vfc_user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;