-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."USER"
(
    "USER_ID" uuid NOT NULL,
    "USER_FNAME" character varying(127),
    "USER_LNAME" character varying(127) NOT NULL,
    "USER_EMAIL" character varying(255) NOT NULL,
    "USER_PASSWORD" character varying(255) NOT NULL,
    PRIMARY KEY ("USER_ID")
);

CREATE TABLE IF NOT EXISTS public."VFLASHCARD_SET"
(
    "VFC_SET_ID" uuid NOT NULL,
    "USER_ID" uuid NOT NULL,
    "VFC_SET_TITLE" character varying(255) NOT NULL,
    PRIMARY KEY ("VFC_SET_ID", "USER_ID")
);

CREATE TABLE IF NOT EXISTS public."VFLASHCARD"
(
    "VFC_ID" uuid NOT NULL,
    "VFC_SET_ID" uuid NOT NULL,
    "VFC_QUESTION" character varying(255) NOT NULL,
    "VFC_ANSWER" character varying(127) NOT NULL,
    PRIMARY KEY ("VFC_ID", "VFC_SET_ID")
);

ALTER TABLE IF EXISTS public."VFLASHCARD_SET"
    ADD CONSTRAINT "USER_ID" FOREIGN KEY ("USER_ID")
    REFERENCES public."USER" ("USER_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."VFLASHCARD"
    ADD CONSTRAINT "VFC_SET_ID" FOREIGN KEY ("VFC_SET_ID")
    REFERENCES public."VFLASHCARD_SET" ("VFC_SET_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;